### ISSUE TITLE
updating deaths for Sweden with higher quality data

### ISSUE THREAD

**Issue by tractatus** [youyanggu/covid19_projections#1]
Hi,

Thanks for an amazing website.

Given the importance of the Swedish strategy to COVID19:

Would it be possible to update the model with more accurate death/day from the Swedish CDC?
The John Hopkins numbers are dated based on day reported and not when the person died so lots of spikes due to lack of reporting during weekends/holidays.

This is an Excel file the official Swedish CDC update every day. However there is a 6-7 day lag in reporting so cases currently are only sort of accurate until 16 April.
https://www.arcgis.com/sharing/rest/content/items/b5e7488e117749c19881cce45db13f7e/data

Form this official Swedish CDC site:
https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/bekraftade-fall-i-sverige/

Current data in JSON:
`let sweden = [{"m-d-y":"3/11/20","deaths":1},{"m-d-y":"3/12/20","deaths":0},{"m-d-y":"3/13/20","deaths":1},{"m-d-y":"3/14/20","deaths":1},{"m-d-y":"3/15/20","deaths":2},{"m-d-y":"3/16/20","deaths":2},{"m-d-y":"3/17/20","deaths":1},{"m-d-y":"3/18/20","deaths":6},{"m-d-y":"3/19/20","deaths":7},{"m-d-y":"3/20/20","deaths":9},{"m-d-y":"3/21/20","deaths":8},{"m-d-y":"3/22/20","deaths":12},{"m-d-y":"3/23/20","deaths":11},{"m-d-y":"3/24/20","deaths":20},{"m-d-y":"3/25/20","deaths":23},{"m-d-y":"3/26/20","deaths":31},{"m-d-y":"3/27/20","deaths":32},{"m-d-y":"3/28/20","deaths":35},{"m-d-y":"3/29/20","deaths":39},{"m-d-y":"3/30/20","deaths":43},{"m-d-y":"3/31/20","deaths":47},{"m-d-y":"4/1/20","deaths":52},{"m-d-y":"4/2/20","deaths":69},{"m-d-y":"4/3/20","deaths":78},{"m-d-y":"4/4/20","deaths":71},{"m-d-y":"4/5/20","deaths":86},{"m-d-y":"4/6/20","deaths":91},{"m-d-y":"4/7/20","deaths":83},{"m-d-y":"4/8/20","deaths":111},{"m-d-y":"4/9/20","deaths":84},{"m-d-y":"4/10/20","deaths":89},{"m-d-y":"4/11/20","deaths":96},{"m-d-y":"4/12/20","deaths":95},{"m-d-y":"4/13/20","deaths":84},{"m-d-y":"4/14/20","deaths":89},{"m-d-y":"4/15/20","deaths":102},{"m-d-y":"4/16/20","deaths":99}]`

**Comment by youyanggu** [comment]
Thank you for sharing this with me, Daniel. I've been focusing on US projections this week, but I will take a look once I have some time.

In the meantime, we have a process in place to smooth out the deaths in cases where there are spikes in reporting (such as with Sweden).

Thanks again for sharing, and stay safe!

**Comment by tractatus** [comment]
No problem. Thanks for the site btw! 
Let me know anytime you decide to shift focus since Sweden has quite a different strategy that might be very informative for the rest of the world very soon regardless if it is successful or not.
Antibody results similar like the one Cuomo released today will probably arrive from Stockholm region within a week. Currently the Swedish CDC has estimated that ~26% (C.I. 11.5 - 50.7) of the greater Stockholm region to be infected by May 1. In your model current estimate for 1 May is 433274 which for Stockholm greater region is ~18% (C.I. 10.54 - 26.81).

**Comment by youyanggu** [comment]
I personally think that number is too high, but we shall see. I think the true number will be closer to 10-15%.
