### ISSUE TITLE
Excess deaths

### ISSUE THREAD

**Issue by ersagunkuruca** [youyanggu/covid19_projections#12]
First, I must say, these projections are really great.

A number of people are looking into excess deaths to determine when exactly the epidemic really started. This project is using official numbers released by governments (which is fine), but maybe another set of projections can be added using excess deaths data. Are there any plans to implement something like this? It would be interesting to see how this affects the projections.

(This is my assumption asking this question: This project uses death data from countries to estimate infection numbers, then predict effective R values, which can be used to generate projections on these numbers. I might be totally wrong about this, correct me if I am. Releasing the code #2 would be helpful to make it clear what approach is taken here.)

**Comment by youyanggu** [comment]
I agree that our projections of reported deaths is an underestimate. There are a lot of existing analysis done on excess deaths, so I recommend you take a look at those. Off the topic of my head, I know the NYT, Financial Times, and The Economist have written articles about it.

We have also open-sourced our underlying SEIR seimulator: https://github.com/youyanggu/yyg-seir-simulator
