### ISSUE TITLE
Actual_deaths spike due to NJ probable deaths inclusion (US_NJ.csv, 2020-06-25)

### ISSUE THREAD

**Issue by mmortal03** [youyanggu/covid19_projections#13]
I noticed that actual_deaths in the US have disproportionately spiked in one day due to yesterday's inclusion of probable deaths by NJ (US_NJ.csv, 2020-06-25).

Here's a news article I found, just to confirm this was NJ's first report of probable deaths in addition to confirmed deaths: https://www.nj.com/coronavirus/2020/06/nj-reports-probable-coronavirus-deaths-for-1st-time-death-toll-now-at-14872-with-170k-total-positive-tests.html

I'm curious if there is a way to incorporate probable deaths without disproportionately throwing them all in a single reporting day? At least from a visual charting perspective, it can be confusing to people. I have no idea if there could be any machine learning projection concerns with it.

**Comment by youyanggu** [comment]
Our data source, Johns Hopkins University CSSE, may end up doing what you suggested. We just take their raw data.

For our modeling, we removed those probable deaths in our training so it does not affect the projections.
