### ISSUE TITLE
Is it possible to publish longer prediction?

### ISSUE THREAD

**Issue by Montana** [youyanggu/covid19_projections#14]
I believe this was already asked, I was wondering if this has changed at all? As I would like obviously publish a longer prediction with some methods I had in mind. 

Thank you,
Montana.

**Comment by youyanggu** [comment]
I think projections more than a few weeks out become fairly noisy, and so we want to avoid making projections if we do not feel confident enough in our results. With school reopenings and the start of flu season in October, it is fairly difficult to estimate where things will be, and for that reason we are currently not extending our forecasts beyond November 1. Thanks for understanding!

**Comment by Montana** [comment]
Makes sense, thank you for the response @youyanggu!
