### ISSUE TITLE
How is the US current Rt 0.96 as of August 7, 2020?

### ISSUE THREAD

**Issue by akchandarana** [youyanggu/covid19_projections#15]
How is the US current Rt 0.96 as of August 7, 2020?

**Comment by dsjoerg** [comment]
What number were you expecting?  Just eyeballing [this](https://ourworldindata.org/coronavirus-data-explorer?yScale=log&zoomToSelection=true&casesMetric=true&interval=smoothed&aligned=true&perCapita=true&smoothing=7&country=~USA&pickerMetric=location&pickerSort=asc), that seems plausible.

**Comment by dsjoerg** [comment]
Or better yet [this](https://ourworldindata.org/coronavirus-data-explorer?yScale=log&zoomToSelection=true&casesMetric=true&interval=smoothed&perCapita=true&smoothing=7&country=~USA&pickerMetric=location&pickerSort=asc).

**Comment by akchandarana** [comment]
@dsjoerg - thanks for both of the links!  Also, apologies for the way I'm now seeing that my overly brief question must have come across.  I know Rt has a confidence interval, some variance in the ways it's calculated depending on who's calculating it and how, how regional/disaggregated Rt won't necessarily roll-up into an aggregated Rt (e.g. on one of the sites I use to get Rt and other coronavirus data on a state-by-state basis, they don't even show an Rt for the US - https://www.covidexitstrategy.org/), etc., but... since so many states in the US are at or around 1.0 with increasing case counts/spread and I've yet to see the US as a whole under 1.0 - https://rt.live & https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html - I was surprised to see the overall Rt for the US under 1.0 for what could be the first time!?  Per the links you sent me, I can see how it could be.

The other source I had primarily been using for Rt by country has had some trouble getting data/keeping their numbers up-to-date recently, which is when I found your data: https://epiforecasts.io/covid/posts/global/

Thanks again for pulling together this data and making it available.  Have a great weekend!
