### ISSUE TITLE
Why the dip in daily vaccinations in May 2021?

### ISSUE THREAD

**Issue by chrisluedtke** [youyanggu/covid19_projections#17]
Not a code issue. Just curious what might explain the massive dip in projected vaccinations in May and June?
![image](https://user-images.githubusercontent.com/20371880/107273639-ef343b80-6a14-11eb-8848-7daed45a139e.png)

**Comment by youyanggu** [comment]
We assume majority of the US adult population will have been vaccinated by June, hence new vaccinations will decline as the US runs out of people to vaccinate.
