### ISSUE TITLE
Request for source

### ISSUE THREAD

**Issue by KirkHadley** [youyanggu/covid19_projections#2]
hi Youyang!

First of all, let me just say that this is marvelous, superbly impressive work. Truly outstanding results, and, imo, orders of magnitude better than the IHME model. I was wondering though, is there any chance of you open sourcing the modeling code? I read your super informative model details page on the site and very much appreciated the explanation there, but I'd still love to see the implementation itself if that's at all possible, though I entirely understand if you choose not do so. Either way, many thanks and much appreciation for your excellent work!

**Comment by youyanggu** [comment]
A lot of the codebase was hastily put together since I only started working on this a month ago. Once I have time to go through it, clean it up and add documentation, I would be happy to release it at some point in the future.

**Comment by dsjoerg** [comment]
Dirty undocumented code is OK too!  :)

The virus's own code is pretty messy and totally undocumented.

**Comment by jasonlouer** [comment]
@youyanggu Thank you for your work on this. If you post the source, you might get some help from the community with the clean up.

**Comment by peterjliu** [comment]
@youyanggu messy code is not a problem; there are plenty to help clean it up. It'll have a bigger impact if others can build off of it.

**Comment by ykzeng** [comment]
Have been playing around epidemic models for a while but looks like I was trying to reinvent the wheel given this wonderful work out here! Do we have any plan to opensource the model now and possibly improve it with the community? Would be super interested to contribute!

**Comment by youyanggu** [comment]
Sorry it took a while, but I recently open-sourced the underlying SEIR simulator behind our model: https://github.com/youyanggu/yyg-seir-simulator. Thanks for being patient.
