### ISSUE TITLE
API Available

### ISSUE THREAD

**Issue by tleonard6** [youyanggu/covid19_projections#3]
Hello, I've read through all of your documentation and that information you're compiling and putting together is impressive.  Do you have an API?  I'm interested in comparing your data to some of the other models. 

Best, 
Taylor

**Comment by youyanggu** [comment]
You can download our raw data/projections from this repository. Are there any data that you can't find?

**Comment by tleonard6** [comment]
No, everything is there and it’s great, thank you.  I was trying to do a better job at automating my pull based on your updates.

**Comment by tleonard6** [comment]
@youyanggu do you happen to project hospitalizations as well?  Or are you focused on new infections/cases and deaths primarily?

**Comment by youyanggu** [comment]
Sorry for the late reply, but we only have projections for true infections and reported deaths.
