### ISSUE TITLE
How to access the noreopen projection data?

### ISSUE THREAD

**Issue by jiweiqi** [youyanggu/covid19_projections#5]
The website added a -noreopen option on May 13, such as https://covid19-projections.com/us-noreopen. The projection is very valuable for analyzing the policy effect. I am wondering how can I access the csv files corresponding to those noreopen projection?

I guess the noreopen projection is made based on the historical projection at someday past? So that I can just go back to download the projection at someday past, say May 13, the projection will be corresponding to the noreopen projection? Am I right?

If you got time, it will be great if you could say more about how does the noreopen projection is made comparing to the normal projection?

**Comment by youyanggu** [comment]
I didn't upload the data for the no-reopen scenarios but if you fill out the Contact form (https://covid19-projections.com/contact), I'll see if I can send it to you.

**Comment by jiweiqi** [comment]
Great. I have just filled the contact form.
