### ISSUE TITLE
Multiple countries, states, and counties in one plot

### ISSUE THREAD

**Issue by chrisvwx** [youyanggu/covid19_projections#7]
This is a wonderful tool!  I'm especially grateful that you have started modeling a few counties.  

I'd love to be able to plot multiple locations in a single plot, say as in the [Data Explorer](https://ourworldindata.org/coronavirus-data-explorer?yScale=log&zoomToSelection=true&casesMetric=true&dailyFreq=true&perCapita=true&smoothing=7&country=GBR+BRA+USA+MEX+SWE) from OurWorldInData.  The OWID tool allows one to select what countries to plot, which I find very useful. This tool also changes the URL to match the selected data, so one can go bookmark the data.  I confess that I don't know how tough this is :-)

Another (much less widely-used) [tool](https://covid-county-dash3.herokuapp.com/)  allows one to compare the NY Times' data for states and counties.  

I'd love to learn if someone has created an online tool to view your data.  If you were to make such plots, I guess your site would be the main place I'd come for COVID-19 data :-)

**Comment by youyanggu** [comment]
Sorry about the delayed reply. I hope someone can create an online tool like you mentioned using our data. All of the data is publicly available! I would do it myself but I think it's more worthwhile for me to focus on the modeling aspect.

**Comment by chrisvwx** [comment]
Thanks for the wonderful site
