### ISSUE TITLE
Fractional death predictions

### ISSUE THREAD

**Issue by chrisvwx** [youyanggu/covid19_projections#9]
great work!

For all countries, states, and counties it appears that the death predictions are rounded to integers before plotting them or putting them into CSV files.  For smaller entities such as [Santa Clara CA](https://covid19-projections.com/us-ca-santa-clara) where the fractional number is between 0 and 1, this creates the awkward case where your predicted total deaths continue to increase while the predicted daily count is 0.  So obviously the internal daily death is a fractional number; I think it would be useful to put this fractional number in the plot and CSV file, as you do for the `R_t` estimates.   Of course this extra information may be distracting in the tooltips on plots for large countries or states, yet in that case you can just show the rounded estimate.

**Comment by youyanggu** [comment]
You can submit a request on our website and I can send you the fractional data. Our reich_forecast directory also has the fraction data for US states.
